/*!
********************************************************************************************
* @file FP_data_cacheProtocolTypes.h
* @brief Protocol public type declarations
********************************************************************************************
* @version           interface data_cache v0.1
*
* @copyright         (C) Copyright EnduroSat
*
*                    Contents and presentations are protected world-wide.
*                    Any kind of using, copying etc. is prohibited without prior permission.
*                    All rights - incl. industrial property rights - are reserved.
*
*-------------------------------------------------------------------------------------------
* GENERATOR: org.endurosat.generators.macchiato.binders.Gen_C v2.12
*-------------------------------------------------------------------------------------------
* !!! Please note that this code is fully GENERATED and shall not be manually modified as
* all changes will be overwritten !!!
********************************************************************************************
*/

#ifndef __FP_DATA_CACHEPROTOCOLTYPES_H__
#define __FP_DATA_CACHEPROTOCOLTYPES_H__

#include <stddef.h>
#include "FP_common/FP_BaseProtocolTypes.h"
#include "FP_common/FP_Helpers.h"
#include "datacache.h"

/**********************************************************************
 *
 *  Shared defines
 *
 **********************************************************************/
#define ES_SAT_FUNC_PROTOCOL_ID_DATA_CACHE ((uint16_t) (0x00000088))

#define DATA_CACHE_GET_OBC_0_DATA_FUNC_ID ((funcIdType_t) 0x00000000)
#define DATA_CACHE_SET_OBC_0_DATA_FUNC_ID ((funcIdType_t) 0x00000001)
#define DATA_CACHE_GET_ADCS_0_DATA_FUNC_ID ((funcIdType_t) 0x00000002)
#define DATA_CACHE_SET_ADCS_0_DATA_FUNC_ID ((funcIdType_t) 0x00000003)
#define DATA_CACHE_GET_ADCS_1_DATA_FUNC_ID ((funcIdType_t) 0x00000004)
#define DATA_CACHE_SET_ADCS_1_DATA_FUNC_ID ((funcIdType_t) 0x00000005)
#define DATA_CACHE_GET_ADCS_2_DATA_FUNC_ID ((funcIdType_t) 0x00000006)
#define DATA_CACHE_SET_ADCS_2_DATA_FUNC_ID ((funcIdType_t) 0x00000007)
#define DATA_CACHE_GET_EPS_0_DATA_FUNC_ID ((funcIdType_t) 0x00000008)
#define DATA_CACHE_SET_EPS_0_DATA_FUNC_ID ((funcIdType_t) 0x00000009)
#define DATA_CACHE_GET_SSP_0_DATA_FUNC_ID ((funcIdType_t) 0x0000000A)
#define DATA_CACHE_SET_SSP_0_DATA_FUNC_ID ((funcIdType_t) 0x0000000B)
#define DATA_CACHE_GET_SSP_1_DATA_FUNC_ID ((funcIdType_t) 0x0000000C)
#define DATA_CACHE_SET_SSP_1_DATA_FUNC_ID ((funcIdType_t) 0x0000000D)
#define DATA_CACHE_GET_SSP_2_DATA_FUNC_ID ((funcIdType_t) 0x0000000E)
#define DATA_CACHE_SET_SSP_2_DATA_FUNC_ID ((funcIdType_t) 0x0000000F)
#define DATA_CACHE_GET_AOCS_CNTRL_TLM_DATA_FUNC_ID ((funcIdType_t) 0x00000010)
#define DATA_CACHE_SET_AOCS_CNTRL_TLM_DATA_FUNC_ID ((funcIdType_t) 0x00000011)
#define DATA_CACHE_GET_OS_TASK_DATA_FUNC_ID ((funcIdType_t) 0x00000012)
#define DATA_CACHE_SET_OS_TASK_DATA_FUNC_ID ((funcIdType_t) 0x00000013)
#define DATA_CACHE_GET_SSP_3_DATA_FUNC_ID ((funcIdType_t) 0x00000014)
#define DATA_CACHE_SET_SSP_3_DATA_FUNC_ID ((funcIdType_t) 0x00000015)
#define DATA_CACHE_GET_SENSOR_MAG_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x00000016)
#define DATA_CACHE_SET_SENSOR_MAG_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x00000017)
#define DATA_CACHE_GET_SENSOR_MAG_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x00000018)
#define DATA_CACHE_SET_SENSOR_MAG_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x00000019)
#define DATA_CACHE_GET_SENSOR_GYRO_DATA_FUNC_ID ((funcIdType_t) 0x0000001A)
#define DATA_CACHE_SET_SENSOR_GYRO_DATA_FUNC_ID ((funcIdType_t) 0x0000001B)
#define DATA_CACHE_GET_SENSOR_COARSE_SUN_DATA_FUNC_ID ((funcIdType_t) 0x0000001C)
#define DATA_CACHE_SET_SENSOR_COARSE_SUN_DATA_FUNC_ID ((funcIdType_t) 0x0000001D)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_MAG_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x0000001E)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_MAG_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x0000001F)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_MAG_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x00000020)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_MAG_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x00000021)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_GYRO_DATA_FUNC_ID ((funcIdType_t) 0x00000022)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_GYRO_DATA_FUNC_ID ((funcIdType_t) 0x00000023)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_CSS_DATA_FUNC_ID ((funcIdType_t) 0x00000024)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_CSS_DATA_FUNC_ID ((funcIdType_t) 0x00000025)
#define DATA_CACHE_GET_ES_ADCS_ESTIMATES_BDOT_DATA_FUNC_ID ((funcIdType_t) 0x00000026)
#define DATA_CACHE_SET_ES_ADCS_ESTIMATES_BDOT_DATA_FUNC_ID ((funcIdType_t) 0x00000027)
#define DATA_CACHE_GET_ES_ADCS_CONTROL_VALUES_MTQ_DATA_FUNC_ID ((funcIdType_t) 0x00000028)
#define DATA_CACHE_SET_ES_ADCS_CONTROL_VALUES_MTQ_DATA_FUNC_ID ((funcIdType_t) 0x00000029)
#define DATA_CACHE_GET_CONOPSFLAGS_DATA_FUNC_ID ((funcIdType_t) 0x0000002A)
#define DATA_CACHE_SET_CONOPSFLAGS_DATA_FUNC_ID ((funcIdType_t) 0x0000002B)
#define DATA_CACHE_GET_AOCS_CNTRL_SYS_STATE_DATA_FUNC_ID ((funcIdType_t) 0x0000002C)
#define DATA_CACHE_SET_AOCS_CNTRL_SYS_STATE_DATA_FUNC_ID ((funcIdType_t) 0x0000002D)
#define DATA_CACHE_GET_ADCS_3_DATA_FUNC_ID ((funcIdType_t) 0x0000002E)
#define DATA_CACHE_SET_ADCS_3_DATA_FUNC_ID ((funcIdType_t) 0x0000002F)
#define DATA_CACHE_GET_ADCS_4_DATA_FUNC_ID ((funcIdType_t) 0x00000030)
#define DATA_CACHE_SET_ADCS_4_DATA_FUNC_ID ((funcIdType_t) 0x00000031)
#define DATA_CACHE_GET_EPS_9_DATA_FUNC_ID ((funcIdType_t) 0x00000032)
#define DATA_CACHE_SET_EPS_9_DATA_FUNC_ID ((funcIdType_t) 0x00000033)
#define DATA_CACHE_GET_EPS_10_DATA_FUNC_ID ((funcIdType_t) 0x00000034)
#define DATA_CACHE_SET_EPS_10_DATA_FUNC_ID ((funcIdType_t) 0x00000035)
#define DATA_CACHE_GET_EPS_14_DATA_FUNC_ID ((funcIdType_t) 0x00000036)
#define DATA_CACHE_SET_EPS_14_DATA_FUNC_ID ((funcIdType_t) 0x00000037)
#define DATA_CACHE_GET_SENSOR_ACC_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x00000038)
#define DATA_CACHE_SET_SENSOR_ACC_PRIMARY_DATA_FUNC_ID ((funcIdType_t) 0x00000039)
#define DATA_CACHE_GET_SENSOR_ACC_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x0000003A)
#define DATA_CACHE_SET_SENSOR_ACC_SECONDARY_DATA_FUNC_ID ((funcIdType_t) 0x0000003B)
#define DATA_CACHE_GET_SENSOR_ACC_PRIMARY_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x0000003C)
#define DATA_CACHE_SET_SENSOR_ACC_PRIMARY_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x0000003D)
#define DATA_CACHE_GET_SENSOR_ACC_SECONDARY_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x0000003E)
#define DATA_CACHE_SET_SENSOR_ACC_SECONDARY_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x0000003F)
#define DATA_CACHE_GET_SENSOR_PANEL_TEMP_DATA_FUNC_ID ((funcIdType_t) 0x00000040)
#define DATA_CACHE_SET_SENSOR_PANEL_TEMP_DATA_FUNC_ID ((funcIdType_t) 0x00000041)
#define DATA_CACHE_GET_SENSOR_PANEL_TEMP_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x00000042)
#define DATA_CACHE_SET_SENSOR_PANEL_TEMP_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x00000043)
#define DATA_CACHE_GET_SENSOR_GYRO_TEMP_DATA_FUNC_ID ((funcIdType_t) 0x00000044)
#define DATA_CACHE_SET_SENSOR_GYRO_TEMP_DATA_FUNC_ID ((funcIdType_t) 0x00000045)
#define DATA_CACHE_GET_SENSOR_GYRO_TEMP_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x00000046)
#define DATA_CACHE_SET_SENSOR_GYRO_TEMP_SAT_FRAME_DATA_FUNC_ID ((funcIdType_t) 0x00000047)
#define DATA_CACHE_GET_CUBEADCS_GEN2_OP_STATUS_COMMON_DATA_FUNC_ID ((funcIdType_t) 0x00000048)
#define DATA_CACHE_SET_CUBEADCS_GEN2_OP_STATUS_COMMON_DATA_FUNC_ID ((funcIdType_t) 0x00000049)
#define DATA_CACHE_GET_CUBEADCS_GEN2_OP_STATUS_APP_DATA_FUNC_ID ((funcIdType_t) 0x0000004A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_OP_STATUS_APP_DATA_FUNC_ID ((funcIdType_t) 0x0000004B)
#define DATA_CACHE_GET_AOCS_CNTRL_REF_PARAMS_DATA_FUNC_ID ((funcIdType_t) 0x0000004C)
#define DATA_CACHE_SET_AOCS_CNTRL_REF_PARAMS_DATA_FUNC_ID ((funcIdType_t) 0x0000004D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_166_DATA_FUNC_ID ((funcIdType_t) 0x0000004E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_166_DATA_FUNC_ID ((funcIdType_t) 0x0000004F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_167_DATA_FUNC_ID ((funcIdType_t) 0x00000050)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_167_DATA_FUNC_ID ((funcIdType_t) 0x00000051)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_168_DATA_FUNC_ID ((funcIdType_t) 0x00000052)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_168_DATA_FUNC_ID ((funcIdType_t) 0x00000053)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_169_DATA_FUNC_ID ((funcIdType_t) 0x00000054)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_169_DATA_FUNC_ID ((funcIdType_t) 0x00000055)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_170_DATA_FUNC_ID ((funcIdType_t) 0x00000056)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_170_DATA_FUNC_ID ((funcIdType_t) 0x00000057)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_171_DATA_FUNC_ID ((funcIdType_t) 0x00000058)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_171_DATA_FUNC_ID ((funcIdType_t) 0x00000059)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_172_DATA_FUNC_ID ((funcIdType_t) 0x0000005A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_172_DATA_FUNC_ID ((funcIdType_t) 0x0000005B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_173_DATA_FUNC_ID ((funcIdType_t) 0x0000005C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_173_DATA_FUNC_ID ((funcIdType_t) 0x0000005D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_174_DATA_FUNC_ID ((funcIdType_t) 0x0000005E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_174_DATA_FUNC_ID ((funcIdType_t) 0x0000005F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_175_DATA_FUNC_ID ((funcIdType_t) 0x00000060)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_175_DATA_FUNC_ID ((funcIdType_t) 0x00000061)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_176_DATA_FUNC_ID ((funcIdType_t) 0x00000062)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_176_DATA_FUNC_ID ((funcIdType_t) 0x00000063)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_177_DATA_FUNC_ID ((funcIdType_t) 0x00000064)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_177_DATA_FUNC_ID ((funcIdType_t) 0x00000065)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_178_DATA_FUNC_ID ((funcIdType_t) 0x00000066)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_178_DATA_FUNC_ID ((funcIdType_t) 0x00000067)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_179_DATA_FUNC_ID ((funcIdType_t) 0x00000068)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_179_DATA_FUNC_ID ((funcIdType_t) 0x00000069)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_180_DATA_FUNC_ID ((funcIdType_t) 0x0000006A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_180_DATA_FUNC_ID ((funcIdType_t) 0x0000006B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_203_DATA_FUNC_ID ((funcIdType_t) 0x0000006C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_203_DATA_FUNC_ID ((funcIdType_t) 0x0000006D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_204_DATA_FUNC_ID ((funcIdType_t) 0x0000006E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_204_DATA_FUNC_ID ((funcIdType_t) 0x0000006F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_205_DATA_FUNC_ID ((funcIdType_t) 0x00000070)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_205_DATA_FUNC_ID ((funcIdType_t) 0x00000071)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_206_DATA_FUNC_ID ((funcIdType_t) 0x00000072)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_206_DATA_FUNC_ID ((funcIdType_t) 0x00000073)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_207_DATA_FUNC_ID ((funcIdType_t) 0x00000074)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_207_DATA_FUNC_ID ((funcIdType_t) 0x00000075)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_208_1_DATA_FUNC_ID ((funcIdType_t) 0x00000076)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_208_1_DATA_FUNC_ID ((funcIdType_t) 0x00000077)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_208_2_DATA_FUNC_ID ((funcIdType_t) 0x00000078)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_208_2_DATA_FUNC_ID ((funcIdType_t) 0x00000079)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_209_DATA_FUNC_ID ((funcIdType_t) 0x0000007A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_209_DATA_FUNC_ID ((funcIdType_t) 0x0000007B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_210_DATA_FUNC_ID ((funcIdType_t) 0x0000007C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_210_DATA_FUNC_ID ((funcIdType_t) 0x0000007D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_211_DATA_FUNC_ID ((funcIdType_t) 0x0000007E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_211_DATA_FUNC_ID ((funcIdType_t) 0x0000007F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_212_DATA_FUNC_ID ((funcIdType_t) 0x00000080)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_212_DATA_FUNC_ID ((funcIdType_t) 0x00000081)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_213_DATA_FUNC_ID ((funcIdType_t) 0x00000082)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_213_DATA_FUNC_ID ((funcIdType_t) 0x00000083)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_214_DATA_FUNC_ID ((funcIdType_t) 0x00000084)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_214_DATA_FUNC_ID ((funcIdType_t) 0x00000085)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_216_DATA_FUNC_ID ((funcIdType_t) 0x00000086)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_216_DATA_FUNC_ID ((funcIdType_t) 0x00000087)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_217_DATA_FUNC_ID ((funcIdType_t) 0x00000088)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_217_DATA_FUNC_ID ((funcIdType_t) 0x00000089)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_218_DATA_FUNC_ID ((funcIdType_t) 0x0000008A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_218_DATA_FUNC_ID ((funcIdType_t) 0x0000008B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_225_DATA_FUNC_ID ((funcIdType_t) 0x0000008C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_225_DATA_FUNC_ID ((funcIdType_t) 0x0000008D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_226_DATA_FUNC_ID ((funcIdType_t) 0x0000008E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_226_DATA_FUNC_ID ((funcIdType_t) 0x0000008F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_165_DATA_FUNC_ID ((funcIdType_t) 0x00000090)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_165_DATA_FUNC_ID ((funcIdType_t) 0x00000091)
#define DATA_CACHE_GET_GNSS_TIME_DATA_FUNC_ID ((funcIdType_t) 0x00000092)
#define DATA_CACHE_SET_GNSS_TIME_DATA_FUNC_ID ((funcIdType_t) 0x00000093)
#define DATA_CACHE_GET_GNSS_BESTXYZ_DATA_FUNC_ID ((funcIdType_t) 0x00000094)
#define DATA_CACHE_SET_GNSS_BESTXYZ_DATA_FUNC_ID ((funcIdType_t) 0x00000095)
#define DATA_CACHE_GET_EPSOVERALLBATTERYINFO_DATA_FUNC_ID ((funcIdType_t) 0x00000096)
#define DATA_CACHE_SET_EPSOVERALLBATTERYINFO_DATA_FUNC_ID ((funcIdType_t) 0x00000097)
#define DATA_CACHE_GET_EPS2_BP_INST0_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x00000098)
#define DATA_CACHE_SET_EPS2_BP_INST0_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x00000099)
#define DATA_CACHE_GET_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x0000009A)
#define DATA_CACHE_SET_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x0000009B)
#define DATA_CACHE_GET_EPS2_BP_INST0_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x0000009C)
#define DATA_CACHE_SET_EPS2_BP_INST0_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x0000009D)
#define DATA_CACHE_GET_EPS2_BP_INST0_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x0000009E)
#define DATA_CACHE_SET_EPS2_BP_INST0_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x0000009F)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000A0)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000A1)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000A2)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000A3)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000A4)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000A5)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000A6)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000A7)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000A8)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000A9)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000AA)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000AB)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000AC)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000AD)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000AE)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000AF)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000B0)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000B1)
#define DATA_CACHE_GET_EPS2_BP_INST1_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000B2)
#define DATA_CACHE_SET_EPS2_BP_INST1_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000B3)
#define DATA_CACHE_GET_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000B4)
#define DATA_CACHE_SET_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000B5)
#define DATA_CACHE_GET_EPS2_BP_INST1_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x000000B6)
#define DATA_CACHE_SET_EPS2_BP_INST1_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x000000B7)
#define DATA_CACHE_GET_EPS2_BP_INST1_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x000000B8)
#define DATA_CACHE_SET_EPS2_BP_INST1_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x000000B9)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000BA)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000BB)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000BC)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000BD)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000BE)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000BF)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000C0)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000C1)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000C2)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000C3)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000C4)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000C5)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000C6)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000C7)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000C8)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000C9)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000CA)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000CB)
#define DATA_CACHE_GET_EPS2_BP_INST2_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000CC)
#define DATA_CACHE_SET_EPS2_BP_INST2_BP_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000CD)
#define DATA_CACHE_GET_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000CE)
#define DATA_CACHE_SET_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000CF)
#define DATA_CACHE_GET_EPS2_BP_INST2_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x000000D0)
#define DATA_CACHE_SET_EPS2_BP_INST2_INA_SENSOR1_DATA_FUNC_ID ((funcIdType_t) 0x000000D1)
#define DATA_CACHE_GET_EPS2_BP_INST2_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x000000D2)
#define DATA_CACHE_SET_EPS2_BP_INST2_INA_SENSOR2_DATA_FUNC_ID ((funcIdType_t) 0x000000D3)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000D4)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000D5)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000D6)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_STATUS_DATA_FUNC_ID ((funcIdType_t) 0x000000D7)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000D8)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_CELLS_INFO_DATA_FUNC_ID ((funcIdType_t) 0x000000D9)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000DA)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_XP_DATA_FUNC_ID ((funcIdType_t) 0x000000DB)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000DC)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_XR_DATA_FUNC_ID ((funcIdType_t) 0x000000DD)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000DE)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_YP_DATA_FUNC_ID ((funcIdType_t) 0x000000DF)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000E0)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_YR_DATA_FUNC_ID ((funcIdType_t) 0x000000E1)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000E2)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_ZP_DATA_FUNC_ID ((funcIdType_t) 0x000000E3)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000E4)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_ZR_DATA_FUNC_ID ((funcIdType_t) 0x000000E5)
#define DATA_CACHE_GET_OBC_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000000)
#define DATA_CACHE_SET_OBC_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000001)
#define DATA_CACHE_GET_ADCS_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000002)
#define DATA_CACHE_SET_ADCS_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000003)
#define DATA_CACHE_GET_ADCS_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000004)
#define DATA_CACHE_SET_ADCS_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000005)
#define DATA_CACHE_GET_ADCS_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000006)
#define DATA_CACHE_SET_ADCS_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000007)
#define DATA_CACHE_GET_EPS_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000008)
#define DATA_CACHE_SET_EPS_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000009)
#define DATA_CACHE_GET_SSP_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000A)
#define DATA_CACHE_SET_SSP_0_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000B)
#define DATA_CACHE_GET_SSP_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000C)
#define DATA_CACHE_SET_SSP_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000D)
#define DATA_CACHE_GET_SSP_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000E)
#define DATA_CACHE_SET_SSP_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000000F)
#define DATA_CACHE_GET_AOCS_CNTRL_TLM_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000010)
#define DATA_CACHE_SET_AOCS_CNTRL_TLM_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000011)
#define DATA_CACHE_GET_OS_TASK_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000012)
#define DATA_CACHE_SET_OS_TASK_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000013)
#define DATA_CACHE_GET_SSP_3_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000014)
#define DATA_CACHE_SET_SSP_3_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000015)
#define DATA_CACHE_GET_SENSOR_MAG_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000016)
#define DATA_CACHE_SET_SENSOR_MAG_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000017)
#define DATA_CACHE_GET_SENSOR_MAG_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000018)
#define DATA_CACHE_SET_SENSOR_MAG_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000019)
#define DATA_CACHE_GET_SENSOR_GYRO_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001A)
#define DATA_CACHE_SET_SENSOR_GYRO_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001B)
#define DATA_CACHE_GET_SENSOR_COARSE_SUN_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001C)
#define DATA_CACHE_SET_SENSOR_COARSE_SUN_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001D)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_MAG_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001E)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_MAG_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000001F)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_MAG_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000020)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_MAG_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000021)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_GYRO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000022)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_GYRO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000023)
#define DATA_CACHE_GET_ES_ADCS_SENSOR_CSS_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000024)
#define DATA_CACHE_SET_ES_ADCS_SENSOR_CSS_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000025)
#define DATA_CACHE_GET_ES_ADCS_ESTIMATES_BDOT_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000026)
#define DATA_CACHE_SET_ES_ADCS_ESTIMATES_BDOT_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000027)
#define DATA_CACHE_GET_ES_ADCS_CONTROL_VALUES_MTQ_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000028)
#define DATA_CACHE_SET_ES_ADCS_CONTROL_VALUES_MTQ_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000029)
#define DATA_CACHE_GET_CONOPSFLAGS_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002A)
#define DATA_CACHE_SET_CONOPSFLAGS_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002B)
#define DATA_CACHE_GET_AOCS_CNTRL_SYS_STATE_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002C)
#define DATA_CACHE_SET_AOCS_CNTRL_SYS_STATE_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002D)
#define DATA_CACHE_GET_ADCS_3_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002E)
#define DATA_CACHE_SET_ADCS_3_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000002F)
#define DATA_CACHE_GET_ADCS_4_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000030)
#define DATA_CACHE_SET_ADCS_4_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000031)
#define DATA_CACHE_GET_EPS_9_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000032)
#define DATA_CACHE_SET_EPS_9_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000033)
#define DATA_CACHE_GET_EPS_10_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000034)
#define DATA_CACHE_SET_EPS_10_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000035)
#define DATA_CACHE_GET_EPS_14_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000036)
#define DATA_CACHE_SET_EPS_14_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000037)
#define DATA_CACHE_GET_SENSOR_ACC_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000038)
#define DATA_CACHE_SET_SENSOR_ACC_PRIMARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000039)
#define DATA_CACHE_GET_SENSOR_ACC_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003A)
#define DATA_CACHE_SET_SENSOR_ACC_SECONDARY_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003B)
#define DATA_CACHE_GET_SENSOR_ACC_PRIMARY_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003C)
#define DATA_CACHE_SET_SENSOR_ACC_PRIMARY_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003D)
#define DATA_CACHE_GET_SENSOR_ACC_SECONDARY_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003E)
#define DATA_CACHE_SET_SENSOR_ACC_SECONDARY_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000003F)
#define DATA_CACHE_GET_SENSOR_PANEL_TEMP_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000040)
#define DATA_CACHE_SET_SENSOR_PANEL_TEMP_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000041)
#define DATA_CACHE_GET_SENSOR_PANEL_TEMP_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000042)
#define DATA_CACHE_SET_SENSOR_PANEL_TEMP_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000043)
#define DATA_CACHE_GET_SENSOR_GYRO_TEMP_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000044)
#define DATA_CACHE_SET_SENSOR_GYRO_TEMP_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000045)
#define DATA_CACHE_GET_SENSOR_GYRO_TEMP_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000046)
#define DATA_CACHE_SET_SENSOR_GYRO_TEMP_SAT_FRAME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000047)
#define DATA_CACHE_GET_CUBEADCS_GEN2_OP_STATUS_COMMON_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000048)
#define DATA_CACHE_SET_CUBEADCS_GEN2_OP_STATUS_COMMON_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000049)
#define DATA_CACHE_GET_CUBEADCS_GEN2_OP_STATUS_APP_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_OP_STATUS_APP_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004B)
#define DATA_CACHE_GET_AOCS_CNTRL_REF_PARAMS_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004C)
#define DATA_CACHE_SET_AOCS_CNTRL_REF_PARAMS_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_166_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_166_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000004F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_167_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000050)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_167_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000051)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_168_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000052)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_168_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000053)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_169_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000054)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_169_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000055)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_170_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000056)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_170_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000057)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_171_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000058)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_171_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000059)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_172_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_172_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_173_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_173_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_174_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_174_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000005F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_175_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000060)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_175_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000061)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_176_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000062)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_176_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000063)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_177_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000064)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_177_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000065)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_178_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000066)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_178_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000067)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_179_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000068)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_179_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000069)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_180_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_180_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_203_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_203_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_204_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_204_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000006F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_205_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000070)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_205_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000071)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_206_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000072)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_206_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000073)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_207_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000074)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_207_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000075)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_208_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000076)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_208_1_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000077)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_208_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000078)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_208_2_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000079)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_209_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_209_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_210_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_210_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_211_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_211_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000007F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_212_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000080)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_212_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000081)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_213_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000082)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_213_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000083)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_214_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000084)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_214_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000085)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_216_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000086)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_216_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000087)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_217_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000088)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_217_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000089)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_218_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008A)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_218_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008B)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_225_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008C)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_225_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008D)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_226_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008E)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_226_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000008F)
#define DATA_CACHE_GET_CUBEADCS_GEN2_TLM_FRAME_165_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000090)
#define DATA_CACHE_SET_CUBEADCS_GEN2_TLM_FRAME_165_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000091)
#define DATA_CACHE_GET_GNSS_TIME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000092)
#define DATA_CACHE_SET_GNSS_TIME_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000093)
#define DATA_CACHE_GET_GNSS_BESTXYZ_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000094)
#define DATA_CACHE_SET_GNSS_BESTXYZ_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000095)
#define DATA_CACHE_GET_EPSOVERALLBATTERYINFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000096)
#define DATA_CACHE_SET_EPSOVERALLBATTERYINFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000097)
#define DATA_CACHE_GET_EPS2_BP_INST0_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000098)
#define DATA_CACHE_SET_EPS2_BP_INST0_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x00000099)
#define DATA_CACHE_GET_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009A)
#define DATA_CACHE_SET_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009B)
#define DATA_CACHE_GET_EPS2_BP_INST0_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009C)
#define DATA_CACHE_SET_EPS2_BP_INST0_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009D)
#define DATA_CACHE_GET_EPS2_BP_INST0_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009E)
#define DATA_CACHE_SET_EPS2_BP_INST0_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x0000009F)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A0)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A1)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A2)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A3)
#define DATA_CACHE_GET_EPS2_BP_INST0_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A4)
#define DATA_CACHE_SET_EPS2_BP_INST0_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A5)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A6)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A7)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A8)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000A9)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AA)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AB)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AC)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AD)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AE)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000AF)
#define DATA_CACHE_GET_EPS2_BP_INST0_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B0)
#define DATA_CACHE_SET_EPS2_BP_INST0_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B1)
#define DATA_CACHE_GET_EPS2_BP_INST1_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B2)
#define DATA_CACHE_SET_EPS2_BP_INST1_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B3)
#define DATA_CACHE_GET_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B4)
#define DATA_CACHE_SET_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B5)
#define DATA_CACHE_GET_EPS2_BP_INST1_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B6)
#define DATA_CACHE_SET_EPS2_BP_INST1_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B7)
#define DATA_CACHE_GET_EPS2_BP_INST1_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B8)
#define DATA_CACHE_SET_EPS2_BP_INST1_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000B9)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BA)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BB)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BC)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BD)
#define DATA_CACHE_GET_EPS2_BP_INST1_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BE)
#define DATA_CACHE_SET_EPS2_BP_INST1_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000BF)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C0)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C1)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C2)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C3)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C4)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C5)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C6)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C7)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C8)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000C9)
#define DATA_CACHE_GET_EPS2_BP_INST1_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CA)
#define DATA_CACHE_SET_EPS2_BP_INST1_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CB)
#define DATA_CACHE_GET_EPS2_BP_INST2_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CC)
#define DATA_CACHE_SET_EPS2_BP_INST2_BP_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CD)
#define DATA_CACHE_GET_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CE)
#define DATA_CACHE_SET_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000CF)
#define DATA_CACHE_GET_EPS2_BP_INST2_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D0)
#define DATA_CACHE_SET_EPS2_BP_INST2_INA_SENSOR1_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D1)
#define DATA_CACHE_GET_EPS2_BP_INST2_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D2)
#define DATA_CACHE_SET_EPS2_BP_INST2_INA_SENSOR2_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D3)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D4)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D5)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D6)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_STATUS_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D7)
#define DATA_CACHE_GET_EPS2_BP_INST2_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D8)
#define DATA_CACHE_SET_EPS2_BP_INST2_BALANCER_CELLS_INFO_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000D9)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DA)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_XP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DB)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DC)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_XR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DD)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DE)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_YP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000DF)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E0)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_YR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E1)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E2)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_ZP_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E3)
#define DATA_CACHE_GET_EPS2_BP_INST2_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E4)
#define DATA_CACHE_SET_EPS2_BP_INST2_CHARGER_ZR_DATA_FUNCRESP_ID ((funcIdType_t) 0x000000E5)

/**********************************************************************
 *
 *  All type definitions used below will be imported from datacache.h!
 *
 **********************************************************************/
typedef dc_data_status_t DATA_CACHE_DCDataStatus_t;
typedef enum
{
    DCDATA_UPDATE_STATUS_ERROR,
    DCDATA_UPDATE_STATUS_OK
} DATA_CACHE_DCDataUpdateStatus_t;


typedef struct {
    DATA_CACHE_OBC_0_t sInput_data;
} PACKED_STRUCT data_cacheset_OBC_0_DataRequestData_t;

typedef struct {
    DATA_CACHE_ADCS_0_t sInput_data;
} PACKED_STRUCT data_cacheset_ADCS_0_DataRequestData_t;

typedef struct {
    DATA_CACHE_ADCS_1_t sInput_data;
} PACKED_STRUCT data_cacheset_ADCS_1_DataRequestData_t;

typedef struct {
    DATA_CACHE_ADCS_2_t sInput_data;
} PACKED_STRUCT data_cacheset_ADCS_2_DataRequestData_t;

typedef struct {
    DATA_CACHE_EPS_0_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS_0_DataRequestData_t;

typedef struct {
    DATA_CACHE_SSP_0_t sInput_data;
} PACKED_STRUCT data_cacheset_SSP_0_DataRequestData_t;

typedef struct {
    DATA_CACHE_SSP_1_t sInput_data;
} PACKED_STRUCT data_cacheset_SSP_1_DataRequestData_t;

typedef struct {
    DATA_CACHE_SSP_2_t sInput_data;
} PACKED_STRUCT data_cacheset_SSP_2_DataRequestData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_TLM_t sInput_data;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_TLM_DataRequestData_t;

typedef struct {
    DATA_CACHE_TaskStats_t sInput_data;
} PACKED_STRUCT data_cacheset_OS_Task_DataRequestData_t;

typedef struct {
    DATA_CACHE_SSP_3_t sInput_data;
} PACKED_STRUCT data_cacheset_SSP_3_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_MAG_PRIMARY_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_MAG_PRIMARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_MAG_SECONDARY_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_MAG_SECONDARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_COARSE_SUN_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_COARSE_SUN_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_MAG_PRIMARY_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_MAG_PRIMARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_MAG_SECONDARY_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_MAG_SECONDARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_GYRO_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_GYRO_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_CSS_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_CSS_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_ESTIMATES_BDOT_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_ESTIMATES_BDOT_DataRequestData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_CONTROL_VALUES_MTQ_t sInput_data;
} PACKED_STRUCT data_cacheset_ES_ADCS_CONTROL_VALUES_MTQ_DataRequestData_t;

typedef struct {
    DATA_CACHE_ConOpsFlags_t sInput_data;
} PACKED_STRUCT data_cacheset_ConOpsFlags_DataRequestData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_SYS_STATE_t sInput_data;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_SYS_STATE_DataRequestData_t;

typedef struct {
    DATA_CACHE_ADCS_3_t sInput_data;
} PACKED_STRUCT data_cacheset_ADCS_3_DataRequestData_t;

typedef struct {
    DATA_CACHE_ADCS_4_t sInput_data;
} PACKED_STRUCT data_cacheset_ADCS_4_DataRequestData_t;

typedef struct {
    DATA_CACHE_EPS_9_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS_9_DataRequestData_t;

typedef struct {
    DATA_CACHE_EPS_10_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS_10_DataRequestData_t;

typedef struct {
    DATA_CACHE_EPS_14_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS_14_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_PRIMARY_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_PRIMARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_SECONDARY_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_SECONDARY_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_PRIMARY_SAT_FRAME_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_PRIMARY_SAT_FRAME_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_SECONDARY_SAT_FRAME_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_SECONDARY_SAT_FRAME_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_PANEL_TEMP_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_PANEL_TEMP_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_PANEL_TEMP_SAT_FRAME_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_PANEL_TEMP_SAT_FRAME_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_TEMP_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_TEMP_DataRequestData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_TEMP_SAT_FRAME_t sInput_data;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_TEMP_SAT_FRAME_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_COMMON_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_OP_STATUS_COMMON_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_APP_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_OP_STATUS_APP_DataRequestData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_REF_PARAMS_t sInput_data;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_REF_PARAMS_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_166_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_166_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_167_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_167_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_168_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_168_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_169_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_169_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_170_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_170_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_171_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_171_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_172_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_172_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_173_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_173_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_174_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_174_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_175_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_175_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_176_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_176_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_177_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_177_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_178_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_178_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_179_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_179_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_180_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_180_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_203_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_203_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_204_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_204_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_205_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_205_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_206_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_206_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_207_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_207_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_1_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_208_1_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_2_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_208_2_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_209_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_209_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_210_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_210_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_211_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_211_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_212_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_212_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_213_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_213_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_214_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_214_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_216_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_216_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_217_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_217_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_218_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_218_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_225_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_225_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_226_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_226_DataRequestData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_165_t sInput_data;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_165_DataRequestData_t;

typedef struct {
    DATA_CACHE_GNSS_TIME_t sInput_data;
} PACKED_STRUCT data_cacheset_GNSS_TIME_DataRequestData_t;

typedef struct {
    DATA_CACHE_GNSS_BESTXYZ_t sInput_data;
} PACKED_STRUCT data_cacheset_GNSS_BESTXYZ_DataRequestData_t;

typedef struct {
    DATA_CACHE_EpsOverallBatteryInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EpsOverallBatteryInfo_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BatteryInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BP_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0DeviceHealthInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0InaSensors1Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_INA_SENSOR1_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0InaSensors2Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_INA_SENSOR2_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerStatusType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_STATUS_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerCellsInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_CELLS_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerXpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_XP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerXrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_XR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerYpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_YP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerYrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_YR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerZpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_ZP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerZrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_ZR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BatteryInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BP_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1DeviceHealthInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1InaSensors1Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_INA_SENSOR1_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1InaSensors2Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_INA_SENSOR2_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerStatusType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_STATUS_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerCellsInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_CELLS_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerXpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_XP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerXrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_XR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerYpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_YP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerYrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_YR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerZpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_ZP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerZrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_ZR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BatteryInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BP_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2DeviceHealthInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2InaSensors1Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_INA_SENSOR1_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2InaSensors2Type_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_INA_SENSOR2_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerStatusType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_STATUS_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerCellsInfoType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_CELLS_INFO_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerXpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_XP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerXrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_XR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerYpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_YP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerYrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_YR_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerZpType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_ZP_DataRequestData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerZrType_t sInput_data;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_ZR_DataRequestData_t;


typedef struct {
    DATA_CACHE_OBC_0_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_OBC_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_OBC_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_ADCS_0_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ADCS_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ADCS_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_ADCS_1_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ADCS_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ADCS_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_ADCS_2_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ADCS_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ADCS_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_EPS_0_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_SSP_0_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SSP_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SSP_0_DataResponseData_t;

typedef struct {
    DATA_CACHE_SSP_1_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SSP_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SSP_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_SSP_2_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SSP_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SSP_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_TLM_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_AOCS_CNTRL_TLM_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_TLM_DataResponseData_t;

typedef struct {
    DATA_CACHE_TaskStats_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_OS_Task_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_OS_Task_DataResponseData_t;

typedef struct {
    DATA_CACHE_SSP_3_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SSP_3_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SSP_3_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_MAG_PRIMARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_MAG_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_MAG_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_MAG_SECONDARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_MAG_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_MAG_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_GYRO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_COARSE_SUN_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_COARSE_SUN_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_COARSE_SUN_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_MAG_PRIMARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_SENSOR_MAG_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_MAG_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_MAG_SECONDARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_SENSOR_MAG_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_MAG_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_GYRO_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_SENSOR_GYRO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_GYRO_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_SENSOR_CSS_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_SENSOR_CSS_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_SENSOR_CSS_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_ESTIMATES_BDOT_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_ESTIMATES_BDOT_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_ESTIMATES_BDOT_DataResponseData_t;

typedef struct {
    DATA_CACHE_ES_ADCS_CONTROL_VALUES_MTQ_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ES_ADCS_CONTROL_VALUES_MTQ_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ES_ADCS_CONTROL_VALUES_MTQ_DataResponseData_t;

typedef struct {
    DATA_CACHE_ConOpsFlags_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ConOpsFlags_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ConOpsFlags_DataResponseData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_SYS_STATE_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_AOCS_CNTRL_SYS_STATE_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_SYS_STATE_DataResponseData_t;

typedef struct {
    DATA_CACHE_ADCS_3_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ADCS_3_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ADCS_3_DataResponseData_t;

typedef struct {
    DATA_CACHE_ADCS_4_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_ADCS_4_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_ADCS_4_DataResponseData_t;

typedef struct {
    DATA_CACHE_EPS_9_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS_9_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS_9_DataResponseData_t;

typedef struct {
    DATA_CACHE_EPS_10_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS_10_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS_10_DataResponseData_t;

typedef struct {
    DATA_CACHE_EPS_14_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS_14_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS_14_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_PRIMARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_ACC_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_PRIMARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_SECONDARY_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_ACC_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_SECONDARY_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_PRIMARY_SAT_FRAME_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_ACC_PRIMARY_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_PRIMARY_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_ACC_SECONDARY_SAT_FRAME_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_ACC_SECONDARY_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_ACC_SECONDARY_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_PANEL_TEMP_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_PANEL_TEMP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_PANEL_TEMP_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_PANEL_TEMP_SAT_FRAME_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_PANEL_TEMP_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_PANEL_TEMP_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_TEMP_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_GYRO_TEMP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_TEMP_DataResponseData_t;

typedef struct {
    DATA_CACHE_SENSOR_GYRO_TEMP_SAT_FRAME_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_SENSOR_GYRO_TEMP_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_SENSOR_GYRO_TEMP_SAT_FRAME_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_COMMON_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_OP_STATUS_COMMON_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_OP_STATUS_COMMON_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_APP_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_OP_STATUS_APP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_OP_STATUS_APP_DataResponseData_t;

typedef struct {
    DATA_CACHE_AOCS_CNTRL_REF_PARAMS_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_AOCS_CNTRL_REF_PARAMS_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_AOCS_CNTRL_REF_PARAMS_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_166_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_166_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_166_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_167_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_167_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_167_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_168_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_168_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_168_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_169_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_169_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_169_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_170_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_170_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_170_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_171_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_171_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_171_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_172_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_172_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_172_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_173_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_173_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_173_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_174_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_174_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_174_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_175_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_175_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_175_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_176_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_176_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_176_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_177_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_177_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_177_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_178_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_178_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_178_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_179_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_179_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_179_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_180_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_180_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_180_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_203_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_203_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_203_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_204_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_204_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_204_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_205_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_205_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_205_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_206_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_206_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_206_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_207_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_207_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_207_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_1_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_208_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_208_1_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_2_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_208_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_208_2_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_209_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_209_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_209_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_210_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_210_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_210_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_211_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_211_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_211_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_212_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_212_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_212_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_213_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_213_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_213_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_214_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_214_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_214_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_216_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_216_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_216_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_217_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_217_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_217_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_218_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_218_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_218_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_225_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_225_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_225_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_226_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_226_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_226_DataResponseData_t;

typedef struct {
    DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_165_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_CUBEADCS_GEN2_TLM_FRAME_165_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_CUBEADCS_GEN2_TLM_FRAME_165_DataResponseData_t;

typedef struct {
    DATA_CACHE_GNSS_TIME_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_GNSS_TIME_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_GNSS_TIME_DataResponseData_t;

typedef struct {
    DATA_CACHE_GNSS_BESTXYZ_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_GNSS_BESTXYZ_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_GNSS_BESTXYZ_DataResponseData_t;

typedef struct {
    DATA_CACHE_EpsOverallBatteryInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EpsOverallBatteryInfo_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EpsOverallBatteryInfo_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BatteryInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0DeviceHealthInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0InaSensors1Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0InaSensors2Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerStatusType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0BalancerCellsInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerXpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerXrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerYpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerYrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerZpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst0ChargerZrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST0_CHARGER_ZR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST0_CHARGER_ZR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BatteryInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1DeviceHealthInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1InaSensors1Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1InaSensors2Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerStatusType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1BalancerCellsInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerXpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerXrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerYpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerYrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerZpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst1ChargerZrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST1_CHARGER_ZR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST1_CHARGER_ZR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BatteryInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BP_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2DeviceHealthInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_DEVICE_HEALTH_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2InaSensors1Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_INA_SENSOR1_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2InaSensors2Type_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_INA_SENSOR2_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerStatusType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_STATUS_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2BalancerCellsInfoType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_BALANCER_CELLS_INFO_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerXpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_XP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerXrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_XR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerYpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_YP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerYrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_YR_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerZpType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_ZP_DataResponseData_t;

typedef struct {
    DATA_CACHE_Eps2Inst2ChargerZrType_t sOutput_data;
    DATA_CACHE_DCDataStatus_t eStatus;
} PACKED_STRUCT data_cacheget_EPS2_BP_INST2_CHARGER_ZR_DataResponseData_t;

typedef struct {
    DATA_CACHE_DCDataUpdateStatus_t eStatus;
} PACKED_STRUCT data_cacheset_EPS2_BP_INST2_CHARGER_ZR_DataResponseData_t;


#endif  // #ifndef __FP_DATA_CACHEPROTOCOLTYPES_H__

