// Header list generated by CMake:
#include "fp/gnss/v1.0/gnss_server/FP_gnssServerApp.h"
#include "fp/Payload_Control/v0.1/Payload_Control_server/FP_Payload_ControlServerApp.h"
#include "fp/nvm_bp/v0.1/nvm_bp_server/FP_nvm_bpServerApp.h"
#include "fp/time/v0.1/time_server/FP_timeServerApp.h"
#include "fp/data_cache/v0.1/data_cache_server/FP_data_cacheServerApp.h"
#include "fp/fault_ops/v0.1/fault_ops_server/FP_fault_opsServerApp.h"
#include "fp/SP/v0.4/SP_client/FP_SPClientApp.h"
#include "fp/MacServices/v0.1/MacServices_server/FP_MacServicesServerApp.h"
#include "fp/ModuleId/v0.1/ModuleId_server/FP_ModuleIdServerApp.h"
#include "fp/ConOps/v0.2/ConOps_server/FP_ConOpsServerApp.h"
#include "fp/FileManager/v1.2/FileManager_server/FP_FileManagerServerApp.h"
#include "fp/nvm/v0.1/nvm_server/FP_nvmServerApp.h"
#include "fp/OBC/v3.4/OBC_server/FP_OBCServerApp.h"
#include "fp/UHF/v0.4/UHF_client/FP_UHFClientApp.h"
#include "fp/EPS1/v0.1/EPS1_client/FP_EPS1ClientApp.h"
#include "fp/EPSII_BP_1/v3.0/EPSII_BP_1_client/FP_EPSII_BP_1ClientApp.h"
#include "fp/EPSII_PDM_1/v1.0/EPSII_PDM_1_client/FP_EPSII_PDM_1ClientApp.h"
#include "fp/OBC_CUBEADCS/v1.1/OBC_CUBEADCS_server/FP_OBC_CUBEADCSServerApp.h"
#include "fp/OBC_AOCS_CNTRL/v1.0/OBC_AOCS_CNTRL_server/FP_OBC_AOCS_CNTRLServerApp.h"
#include "fp/OBC_CUBEADCS_GEN2/v1.0/OBC_CUBEADCS_GEN2_server/FP_OBC_CUBEADCS_GEN2ServerApp.h"
#include "fp/Telemetry/v0.1/Telemetry_server/FP_TelemetryServerApp.h"
#include "fp/Beacons/v0.1/Beacons_server/FP_BeaconsServerApp.h"
#include "fp/crypto/v0.1/crypto_server/FP_cryptoServerApp.h"
#include "fp/SBAND_TMTC/v1.1/SBAND_TMTC_client/FP_SBAND_TMTCClientApp.h"
#include "fp/SDS/v0.3/SDS_server/FP_SDSServerApp.h"
#include "fp/OBC_ES_COORDSYS/v3.0/OBC_ES_COORDSYS_server/FP_OBC_ES_COORDSYSServerApp.h"
#include "fp/OBC_ES_ADCS/v3.0/OBC_ES_ADCS_server/FP_OBC_ES_ADCSServerApp.h"
#include "fp/OBC_ACTUATOR_CONTROL_SERVICE/v3.0/OBC_ACTUATOR_CONTROL_SERVICE_server/FP_OBC_ACTUATOR_CONTROL_SERVICEServerApp.h"
#include "fp/OBC_ADIS16265_GYRO/v3.0/obc_adis16265_gyro_server/FP_obc_adis16265_gyroServerApp.h"
#include "fp/obc_micropython/v1.1/obc_micropython_server/FP_obc_micropythonServerApp.h"

// A wrapper function, which calls the init functions of all the enabled services
inline void ESSA_Stack_Services_Init()
{
    // Functions generated by CMake:
    gnssServerAppInit();
    Payload_ControlServerAppInit();
    nvm_bpServerAppInit();
    timeServerAppInit();
    data_cacheServerAppInit();
    fault_opsServerAppInit();
    SPClientAppInit();
    MacServicesServerAppInit();
    ModuleIdServerAppInit();
    ConOpsServerAppInit();
    FileManagerServerAppInit();
    nvmServerAppInit();
    OBCServerAppInit();
    UHFClientAppInit();
    EPS1ClientAppInit();
    EPSII_BP_1ClientAppInit();
    EPSII_PDM_1ClientAppInit();
    OBC_CUBEADCSServerAppInit();
    OBC_AOCS_CNTRLServerAppInit();
    OBC_CUBEADCS_GEN2ServerAppInit();
    TelemetryServerAppInit();
    BeaconsServerAppInit();
    cryptoServerAppInit();
    SBAND_TMTCClientAppInit();
    SDSServerAppInit();
    OBC_ES_COORDSYSServerAppInit();
    OBC_ES_ADCSServerAppInit();
    OBC_ACTUATOR_CONTROL_SERVICEServerAppInit();
    obc_adis16265_gyroServerAppInit();
    obc_micropythonServerAppInit();
}
