// Header list generated by CMake:
#include "fp/gnss/v1.0/gnss_server/FP_gnssProtocolServer.h"
#include "fp/Payload_Control/v0.1/Payload_Control_server/FP_Payload_ControlProtocolServer.h"
#include "fp/nvm_bp/v0.1/nvm_bp_server/FP_nvm_bpProtocolServer.h"
#include "fp/time/v0.1/time_server/FP_timeProtocolServer.h"
#include "fp/data_cache/v0.1/data_cache_server/FP_data_cacheProtocolServer.h"
#include "fp/fault_ops/v0.1/fault_ops_server/FP_fault_opsProtocolServer.h"
#include "fp/SP/v0.4/SP_client/FP_SPProtocolClient.h"
#include "fp/MacServices/v0.1/MacServices_server/FP_MacServicesProtocolServer.h"
#include "fp/ModuleId/v0.1/ModuleId_server/FP_ModuleIdProtocolServer.h"
#include "fp/ConOps/v0.2/ConOps_server/FP_ConOpsProtocolServer.h"
#include "fp/FileManager/v1.2/FileManager_server/FP_FileManagerProtocolServer.h"
#include "fp/nvm/v0.1/nvm_server/FP_nvmProtocolServer.h"
#include "fp/OBC/v3.4/OBC_server/FP_OBCProtocolServer.h"
#include "fp/UHF/v0.4/UHF_client/FP_UHFProtocolClient.h"
#include "fp/EPS1/v0.1/EPS1_client/FP_EPS1ProtocolClient.h"
#include "fp/EPSII_BP_1/v3.0/EPSII_BP_1_client/FP_EPSII_BP_1ProtocolClient.h"
#include "fp/EPSII_PDM_1/v1.0/EPSII_PDM_1_client/FP_EPSII_PDM_1ProtocolClient.h"
#include "fp/OBC_CUBEADCS/v1.1/OBC_CUBEADCS_server/FP_OBC_CUBEADCSProtocolServer.h"
#include "fp/OBC_AOCS_CNTRL/v1.0/OBC_AOCS_CNTRL_server/FP_OBC_AOCS_CNTRLProtocolServer.h"
#include "fp/OBC_CUBEADCS_GEN2/v1.0/OBC_CUBEADCS_GEN2_server/FP_OBC_CUBEADCS_GEN2ProtocolServer.h"
#include "fp/Telemetry/v0.1/Telemetry_server/FP_TelemetryProtocolServer.h"
#include "fp/Beacons/v0.1/Beacons_server/FP_BeaconsProtocolServer.h"
#include "fp/crypto/v0.1/crypto_server/FP_cryptoProtocolServer.h"
#include "fp/SBAND_TMTC/v1.1/SBAND_TMTC_client/FP_SBAND_TMTCProtocolClient.h"
#include "fp/SDS/v0.3/SDS_server/FP_SDSProtocolServer.h"
#include "fp/OBC_ES_COORDSYS/v3.0/OBC_ES_COORDSYS_server/FP_OBC_ES_COORDSYSProtocolServer.h"
#include "fp/OBC_ES_ADCS/v3.0/OBC_ES_ADCS_server/FP_OBC_ES_ADCSProtocolServer.h"
#include "fp/OBC_ACTUATOR_CONTROL_SERVICE/v3.0/OBC_ACTUATOR_CONTROL_SERVICE_server/FP_OBC_ACTUATOR_CONTROL_SERVICEProtocolServer.h"
#include "fp/OBC_ADIS16265_GYRO/v3.0/obc_adis16265_gyro_server/FP_obc_adis16265_gyroProtocolServer.h"
#include "fp/obc_micropython/v1.1/obc_micropython_server/FP_obc_micropythonProtocolServer.h"

// Define generated by CMake
// Comma separated function names of the handlers of all the enabled protocols
// Used to initialize a static array of function pointers
#define FUNCTION_PROTOCOL_HANDLERS_LIST \
    &FP_gnssProtocolServerInfo, \
    &FP_Payload_ControlProtocolServerInfo, \
    &FP_nvm_bpProtocolServerInfo, \
    &FP_timeProtocolServerInfo, \
    &FP_data_cacheProtocolServerInfo, \
    &FP_fault_opsProtocolServerInfo, \
    &FP_SPProtocolClientInfo, \
    &FP_MacServicesProtocolServerInfo, \
    &FP_ModuleIdProtocolServerInfo, \
    &FP_ConOpsProtocolServerInfo, \
    &FP_FileManagerProtocolServerInfo, \
    &FP_nvmProtocolServerInfo, \
    &FP_OBCProtocolServerInfo, \
    &FP_UHFProtocolClientInfo, \
    &FP_EPS1ProtocolClientInfo, \
    &FP_EPSII_BP_1ProtocolClientInfo, \
    &FP_EPSII_PDM_1ProtocolClientInfo, \
    &FP_OBC_CUBEADCSProtocolServerInfo, \
    &FP_OBC_AOCS_CNTRLProtocolServerInfo, \
    &FP_OBC_CUBEADCS_GEN2ProtocolServerInfo, \
    &FP_TelemetryProtocolServerInfo, \
    &FP_BeaconsProtocolServerInfo, \
    &FP_cryptoProtocolServerInfo, \
    &FP_SBAND_TMTCProtocolClientInfo, \
    &FP_SDSProtocolServerInfo, \
    &FP_OBC_ES_COORDSYSProtocolServerInfo, \
    &FP_OBC_ES_ADCSProtocolServerInfo, \
    &FP_OBC_ACTUATOR_CONTROL_SERVICEProtocolServerInfo, \
    &FP_obc_adis16265_gyroProtocolServerInfo, \
    &FP_obc_micropythonProtocolServerInfo
