/*
 * Copyright (c) 2020-2022 EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 */
/*
 * nvm_block_ids.h
 *
 *  Created on: Jun 29, 2021
 *      Author: Ivan Petrov
 */

#ifndef NVM_INC_NVM_APP_BLOCK_IDS_H_
#define NVM_INC_NVM_APP_BLOCK_IDS_H_

#include "nvm_bootcfg/inc/nvm_boot_block_ids.h"

enum
{
    NVM_RESERVED = NVM_BOOT_BLOCK_MAX_COUNT,
    NVM_BLOCK_BEACONS_GENERAL,
    NVM_BLOCK_BEACONS_PRESETS,
    NVM_APP_BLOCK_CONOPS_CONFIG,
    NVM_APP_BLOCK_CONOPS_IDLE_CONFIG,
    NVM_BLOCK_TELEMETRY_GENERAL,
    NVM_BLOCK_TELEMETRY_PRESETS,
    NVM_BLOCK_TELEMETRY_FILE_CFG,
    NVM_BLOCK_EPS_M_CONFIG,
    NVM_BLOCK_CUBEADCS_ERR_HANDL_CONFIG,
    NVM_BLOCK_CUBEADCS_STATUS,
    NVM_BLOCK_I2C_CONFIG,
    NVM_BLOCK_CUBEADCS_ANGLE_LIMITS,
    NVM_BLOCK_ES_ADCS_CONFIG,
    NVM_BLOCK_AOCS_PM_CONFIG,
	NVM_BLOCK_AOCS_PM_THRESHOLDS,
    NVM_BLOCK_COORDINATE_FRAMES,
    NVM_BLOCK_SDS_SENS_READ_FREQ_CFG,
    NVM_BLOCK_CRYPTO_CFG,
    NVM_BLOCK_CUBEADCS_SIMULATION_MODE,
    NVM_BLOCK_RTC_CALIB_DATA,
    NVM_BLOCK_GYROSCOPE_CONFIG,
    NVM_FF_STATS,
	NVM_BLOCK_CUBEADCS_SYS_STATE_CFG,
	NVM_MAC_ADDRESS_BOOK,
    NVM_BLOCK_CUBEADCS_GEN2_SYS_STATE_CFG,
    NVM_BLOCK_CUBEADCS_GEN2_TLM_CFG,
    NVM_BLOCK_ADCS_CMS_STATUS,
    NVM_BLOCK_FAULT_INDEX,
    NVM_BLOCK_FAULT_DATA0,
    NVM_BLOCK_FAULT_DATA1,
    NVM_BLOCK_FAULT_DATA2,
    NVM_BLOCK_FAULT_DATA3,
    NVM_BLOCK_FAULT_DATA4,
    NVM_BLOCK_MAX_COUNT
};

#endif /* NVM_INC_NVM_APP_BLOCK_IDS_H_ */
