@startuml
title Attitude and Orbit Control Overview

package "Ground Segment" {
:Operator: as op
}

package "Satellite" {

[payload_scheduler] as PS
[conops]
[payload_ctrl] as PC

[aocs_cntrl] as AC
[cubeadcs] as gen_1
[cubeadcs_gen2] as gen_2
[libcubeobc] as gen_2_drv
[es_adcs]
() "<b>if_aocs_cntrl.h" as if_aocs
}

op ..up..> PS : update\non-board\nschedule

PS .> conops : pass AOCS state and params from schedule
conops .> PC : trigger payload activation with params
PC ..> conops : notify payload events
PC ..> [AC] : trigger and monitor AOCS pointing
AC -right-> if_aocs : request ADCS state change
gen_1 -up- if_aocs : <i>0..1
gen_2 -up- if_aocs : <i>0..1
gen_2 -down- gen_2_drv
es_adcs -up- if_aocs : <i>0..1
op .> AC : <i>optional direct control via FIDL

note right of PS
    <i>Each entry in the binary schedule file
    <i>contains AOCS state and pointing parameters.
end note

note left of PC
	<i> User payloads are omitted from this
	<i> diagram for clarity purposes.
end note

@enduml