@startuml
Interface IDataCache as "Data Interface"
IDataCache -down- [DataCache]
[Data Producer] .right.> IDataCache: <i><<<b>dc_set_<data name>_data</b>(...)>></i>
[Data Consumer 2] .left.> IDataCache: <i><<<b>dc_get_<data name>_data</b>(...)>></i>
[Data Consumer 1] .left.> IDataCache: <i><<<b>dc_get_<data name>_data</b>(...)>></i>
@enduml