@startuml
folder DataCache as "<OBC SDK>/espf/config/datacache" {
file dc as "DataCache.fidl"
file dc_types as "DataCache_Types.fidl"
file dc_depl as "deploy_dc.fdepl"
}

dc_depl ..> dc: <i><<imports>></i>
dc ..> dc_types: <i><<imports>></i>
@enduml