@startuml

participant User as "User code"
participant RTOS
participant ESTTC as "ESTTC.c"

User -> ESTTC: ESTTC_Init()
note over ESTTC: initialize component RAM and related HW
User -> ESTTC: ESTTC_InitTask()
note over ESTTC: activate OS polling task
loop preemptive OS task
note over ESTTC: all received commands are serviced by the OS task
RTOS -> ESTTC: ESTTC_UART_TASK()
activate ESTTC
    note left User: ESTTC_Notif_OnEvent() weak callback can be\nredefined by users in case\nthey need to know when certain ESTTC\nevents occur.
    opt if new ESTTC packet received
        ESTTC -> User: ESTTC_Notif_OnEvent(ESTTC_EVENT_RX_PACKET_ON_INTERFACE, <interface ID>)
    else if last received ESTTC packet processing finished
        ESTTC -> User: ESTTC_Notif_OnEvent(ESTTC_EVENT_PACKET_SERVED_OK, <interface ID>)
    end opt
deactivate ESTTC
end loop

@enduml