@startuml
start
:Initialization;
package "Step 1 " {
: Read active magnetometer frame ;
}
package "Step 2 " {
:   Verify that the frame is incorrect   ;
}
package "Step 3 " {
:    Set new magnetometer frame    ;
}
package "Step 4 " {
:Save the new active frame to NVM ;
}
@enduml
