@startuml

skinparam rectangle {
    roundCorner<<Concept>> 45
}

Actor Developer
artifact C_src as "C source files"
artifact py_src as "Python API bindings"
artifact js_src as "JavaScript GUI API bindings"
file fdepl as "FDEPL (deployment schema) file"
file fidl as "FIDL files"
package OBC as "SDK"

[macchiato] --> fdepl: (1) parse
[macchiato] --> fidl: (2) parse
[macchiato] --> C_src: (3) generate/merge sources
[macchiato] ..> py_src: <i>optional</i>
[macchiato] ..> js_src: <i>optional</i>
Developer --> C_src: (4) fill-in generated command templates
OBC -> C_src: (5) include in build and\nregister to ESPS I stack
Developer --> OBC: (6) build and enjoy!

@enduml
