@startwbs
* <b>macaron</b>\nbuild\nwrapper
** CMake
*** macchiato
**** FIDL-generated C source code
*** ninja
**** build artifacts (.elf, .bin, .map, .list)
** other artifacts
*** build (error) logs

@endwbs
