@startuml
title OBC payload control mechanism overview

package "Ground Segment" {
:Operator: as op
}

package "Satellite" {
[payload_scheduler] as PS
[conops]
[aocs]
[payload_ctrl] as PC
[user_payload] as UP
() "<b>if_payload_control.h" as if_pc
}

op ..up..> PS : update\non-board\nschedule

PS .up.> conops : notify scheduled event
conops ..> PC : trigger payload activation
PC -up-> if_pc : trigger payload operation
PC ..> conops : notify payload events
PC ..> [aocs] : trigger and monitor AOCS pointing
UP -down- if_pc : <i>1..n

note bottom of PS
    <i>A full on-board schedule can be loaded as a
    <i>binary file. Individual schedule entries can
    <i>be added via a FIDL command as well.
end note
@enduml