@startuml
title Payload control start/stop sequence overview

actor "Ground Operator" as GO
participant payload_scheduler as PS
participant conops as CO
participant payload_ctrl as PC
participant aocs as AOCS
participant user_payload as UP

GO ->> PS: upload schedule file

PS -> PS: load new schedule

== schedule entry start time reached for payload #pid ==
PS -> CO: indicate that #pid payload\nshall be activated

opt ConOps state is <b>Idle</b> and operational conditions are fulfilled
CO -> PC: request payload #pid activation
PC -> AOCS: activate pointing mode for\n #pid payload

AOCS -> AOCS: start monitoring\npointing parameters

opt pointing mode established
AOCS ->> PC: notify pointing mode ready
PC -> UP: <b>if_payload_control.h::start(...)
UP ->> PC: <b>p_payload_event({ #pid, PL_STATE_STARTED, 0 })
end opt
end opt

== schedule entry end time reached for payload #pid ==
PS -> CO: indicate that #pid payload\nshall be deactivated
CO -> PC: request payload #pid deactivation

PC -> UP: <b>if_payload_control.h::stop(...)
UP ->> PC: <b>p_payload_event({ #pid, PL_STATE_STOPPED, 0 })

@enduml