@startuml
title State change sequence step

start

repeat: Sequence step;
  :Check action;
  :Set action;
  if (Change successful?) then (yes)
    :Execute the next step in the sequence;
    stop
  else (no)
  endif
repeat while (Attempted **3** times?) is (no) not (yes)

:Exit **StateChange State** and invoke the **FDIR State**;

stop

@enduml