@startuml
hide empty description

[*] --> ALIVE
ALIVE --> MISSING: [alive timer > UHF_KEEP_ALIVE_TASK_PERIOD_SECONDS]
MISSING --> RESET: / power reset UHF and reset UHF timeout
RESET --> SWITCHING: [timeout expired] / perform another reset
SWITCHING --> ALIVE: [timeout expired] / switch to another UHF if available
[H] --> ALIVE: UHF pong response received / reset timeout

@enduml