@startuml

title ESPS I Project structure

card card [
<b>User Application</b>: User application logic.
====
<b>Function Protocol</b>: Generated protocols with pre-defined commands.
====
<b>ESPS I</b>: Accomplish communication between corresponding network layers on two or more interconnected devices.
====
<b>ESPS I MAC Drivers</b>: Send/Receive mechanism for RS-485 protocol.
====
<b>HAL Drivers</b>: Interface to the STM32xx microprocessor peripherals.
]

@enduml
