@startuml

title ESPS Driver RX State Machine

' List of states
[eMACReceive_Off]
[eMACReceive_Idle]
[eMACReceive_NewMessage]
[eMACReceive_WaitAddress]
[eMACReceive_ReadHeader]
[eMACReceive_ReadData]
[eMACReceive_ReadCRC]
[eMACReceive_DispatchMessage]

legend right
- eRXEvent_None: After a transition is complete
- eRXEvent_Activated: After initialization of the UART or processing IDLE state
- eRXEvent_NewMessage: When processing New Message state
- eRXEvent_WaitTimeout: When RX timer expires
- eRXEvent_AddressReceived: UART received a valid address
- eRXEvent_ReceptionComplete: UART received a valid byte
- eRXEvent_MessageDispatched: RX memory pool is free, the message is dispatched
- eRXEvent_TxOpStarted: A transfer started
- eRXEvent_TxOpFinished: A transfer finished either successfully or due to an error in UART
- eRXEvent_RxError: Error detected in the UART while receiving
endlegend

[eMACReceive_Off]           -> [eMACReceive_Idle]          : fs_vInitInterface()

[eMACReceive_Idle]          -> [eMACReceive_NewMessage]    : eRXEvent_Activated

[eMACReceive_NewMessage]    --> [eMACReceive_WaitAddress]   : eRXEvent_NewMessage
[eMACReceive_NewMessage]    --> [eMACReceive_NewMessage]    : Any other event than eRXEvent_NewMessage

[eMACReceive_WaitAddress]   --> [eMACReceive_ReadHeader]    : eRXEvent_AddressReceived
[eMACReceive_WaitAddress]   --> [eMACReceive_WaitAddress]   : eRXEvent_TxOpStarted
[eMACReceive_WaitAddress]   --> [eMACReceive_WaitAddress]   : eRXEvent_TxOpFinished

[eMACReceive_ReadHeader]    -> [eMACReceive_ReadData]      : eRXEvent_ReceptionComplete + VALID CRC
[eMACReceive_ReadHeader]    -> [eMACReceive_WaitAddress]   : eRXEvent_ReceptionComplete + INVALID CRC
[eMACReceive_ReadHeader]    -> [eMACReceive_ReadHeader]    : eRXEvent_AddressReceived
[eMACReceive_ReadHeader]    -> [eMACReceive_WaitAddress]   : eRXEvent_RxError

[eMACReceive_ReadData]      --> [eMACReceive_ReadCRC]       : eRXEvent_ReceptionComplete
[eMACReceive_ReadData]      --> [eMACReceive_WaitAddress]   : eRXEvent_WaitTimeout
[eMACReceive_ReadData]      --> [eMACReceive_ReadHeader]    : eRXEvent_AddressReceived
[eMACReceive_ReadData]      --> [eMACReceive_WaitAddress]   : eRXEvent_RxError

[eMACReceive_ReadCRC]       -> [eMACReceive_DispatchMessage] : eRXEvent_ReceptionComplete
[eMACReceive_ReadCRC]       -> [eMACReceive_WaitAddress]     : eRXEvent_WaitTimeout
[eMACReceive_ReadCRC]       -> [eMACReceive_ReadHeader]      : eRXEvent_AddressReceived
[eMACReceive_ReadCRC]       -> [eMACReceive_WaitAddress]     : eRXEvent_RxError

[eMACReceive_DispatchMessage] --> [eMACReceive_NewMessage]  : eRXEvent_MessageDispatched

@enduml
